version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  AfterInstall:
    - location: npm install
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: npm start
      timeout: 30
      runas: ubuntu
