version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: npm install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: npm start #start script for the website
      timeout: 300
      runas: root
