version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Start test
      - npm test
artifacts:
  files:
    - start.js
    - main.js
    - graphql.config.json
    - .graphqlconfig
    - .env
    - LICENSE
    - package.json
    - README.md
    - package-lock.json
    - appspec.yml
    - schemas/*
    - resolvers/*
    - models/*
    - config/*
  discard-paths: yes